### ISSUE TITLE
bcrypt_elixir not compiling

### ISSUE THREAD

**Issue by melissable** [chernyshof/react-phoenix-users-boilerplate#12]
Hello!

I'm struggling to get this to run.

Elixir / Hex version (mix hex.info):
Hex: 0.17.7
Elixir: 1.6.6
OTP: 20.2
Built with: Elixir 1.6.4 and OTP 19.3

Node / NPM version (node -v) (npm -v): 6.14.3 / 6.1.0
Operating system: Windows

After mix deps.get and npm install,
Ran mix phx.server and got the following message:

```
$ mix phx.server
==> bcrypt_elixir
could not compile dependency :bcrypt_elixir, "mix compile" failed. You can recompile this dependency with "mix deps.compile bcrypt_elixir", update it with "mix deps.update bcrypt_elixir" or clean it with "mix deps.clean bcrypt_elixir"
==> boilerplate
** (Mix) "nmake" not found in the path. If you have set the MAKE environment variable,
please make sure it is correct.
```

I've tried all three of the suggestions on bcrypt_elixir and reran the mix deps.get, npm install, phx.server and still no luck. 

Your help with this would be greatly appreciated.

Thank you!
Melissa

**Comment by chernyshof** [comment]
Hi
Have you tried this guide? https://github.com/riverrun/comeonin/wiki/Requirements#windows
Let me know if this does not help you

**Comment by chernyshof** [comment]
I close this issue
Feel free to re-open it if this solution does not help you
